import { ObjectClass } from './object-class'

export type User = {
  dn: string
  objectClass: ObjectClass[]
  cn: string
  sn: string
  description: string
  physicalDeliveryOfficeName: string
  distinguishedName: string
  instanceType: string
  whenCreated: string
  whenChanged: string
  displayName: string
  uSNCreated: string
  memberOf: string[]
  uSNChanged: string
  department: string
  proxyAddresses: string[]
  name: string
  objectGUID: string
  userAccountControl: string
  badPwdCount: string
  codePage: string
  countryCode: string
  employeeID: string
  homeDirectory: string
  homeDrive: string
  badPasswordTime: string
  lastLogoff: string
  lastLogon: string
  pwdLastSet: string
  primaryGroupID: string
  objectSid: string
  accountExpires: string
  logonCount: string
  sAMAccountName: string
  sAMAccountType: string
  showInAddressBook: string[]
  legacyExchangeDN: string
  userPrincipalName: string
  lockoutTime: string
  objectCategory: string
  dSCorePropagationData: string[]
  'mS-DS-ConsistencyGuid': string
  lastLogonTimestamp: string
  'msDS-RevealedDSAs': string[]
  mail: string
  thumbnailPhoto: string
  msExchRBACPolicyLink: string
  msExchDumpsterWarningQuota: string
  msExchUserAccountControl: string
  msExchSafeSendersHash: string
  'msDS-ExternalDirectoryObjectId': string
  msExchRecipientDisplayType: string
  msExchTextMessagingState: string[]
  msExchCalendarLoggingQuota: string
  msExchWhenMailboxCreated: string
  msExchMailboxSecurityDescriptor: string
  msExchPoliciesIncluded: string[]
  msExchRecipientTypeDetails: string
  msExchArchiveWarnQuota: string
  msExchELMailboxFlags: string
  msExchVersion: string
  msExchMailboxGuid: string
  msExchMobileMailboxFlags: string
  msExchUserCulture: string
  mailNickname: string
  msExchDumpsterQuota: string
  msExchUMDtmfMap: string[]
  msExchArchiveQuota: string
  msExchHomeServerName: string
  homeMDB: string
  mDBUseDefaults: string
} & Record<`extensionAttribute${number}`, string | undefined>
